name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: run tests on chrome
        uses: cypress-io/github-action@v6
        with:    
          build: npm run build 
          start: npm test
          browser: chrome

      - name: run tests on firefox
        uses: cypress-io/github-action@v6
        with:    
          build: npm run build 
          start: npm test
          browser: firefox    

      - name: Download html report
        uses: actions/upload-artifact@v2
        with:
          name: output report
          path: /home/runner/work/LearningCypress/LearningCypress/cypress/reports/html