name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      # - name: Cypress run
      #   uses: cypress-io/github-action@v4
      #   with:
      #     # runTests: false
      #     build: npm install --save-dev cypress
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:    
          build: npm install 
          start: npm test
          browser: chrome
