name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Execute tests
        uses: cypress-io/github-action@v4
        with:    
          build: npm run build 
          start: npm test
          browser: chrome

      - name: Download html report
        uses: actions/upload-artifact@v2
        with:
          name: my-artifacts
          path: /home/runner/work/LearningCypress/LearningCypress/cypress/reports/html
